# Configurations
title:            C++ OpenBook
longtitle:        Programming and Problem Solving with C++
author:           Dr. Alireza Manashty
email:            a.r.manashty@gmail.com
description: >
  University of Regina

version:          1.0
gitbook_version:  3.2.3

url:              'https://staging.urdatascience.ca/'
baseurl:          ''
rss:              RSS

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

markdown_ext:     markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink:        /:title:output_ext

exclude:
  - _drafts

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jemoji
